server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///vhr?useServerPrepStmts=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    default-property-inclusion: non_null

  redis:
    host: localhost
    port: 6379
    database: 0

  cache:
    cache-names:
      - menu
    redis:
      time-to-live: 1M

mybatis-plus:
  type-aliases-package: com.csl.vhr.entity
